language: php
php:
- "7.2"
- "7.3"
services:
- mysql

before_script:
- composer self-update
- composer install --no-interaction
- phpenv rehash

install:
- composer self-update
- composer install

cache:
  directories:
  - $HOME/.composer/cache

script:
- vendor/bin/phpunit --coverage-text

notifications:
  email:
    on_success: always
    on_failure: always